# fly.toml app configuration file generated for call-me-button on 2023-12-08T23:15:02+06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "call-me-button"
primary_region = "sin"

[build]

[env]
  PORT = "3001"
  SHOPIFY_APP_URL = "https://call-me-button.fly.dev"
  SHOPIFY_API_KEY = "b863a8bdd5abdf273a317392f7266455"
  SCOPES = "write_products"

[http_service]
  internal_port = 3001

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
