# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "call-me-button"
client_id = "dcb0d6d8053b9e8be0bbdc5f97de4f2d"
application_url = "https://beautifully-chicks-prophet-amsterdam.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://beautifully-chicks-prophet-amsterdam.trycloudflare.com/auth/callback",
  "https://beautifully-chicks-prophet-amsterdam.trycloudflare.com/auth/shopify/callback",
  "https://beautifully-chicks-prophet-amsterdam.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "devrisen.myshopify.com"
